---
- name: Set username, if not defined
  set_fact:
    logstash_system_username: logstash_internal
  when: logstash_auto_create_elastic_user and logstash_system_username == ""

- name: Create writer role in Elasticsearch
  uri:
    url: "{{ logstash_elasticsearch_hosts | first }}/_security/role/{{ logstash_auto_create_role_name }}"
    method: POST
    body_format: json
    body: "{{ logstash_auto_create_role_request_settings }}"
    status_code: 200
    user: "{{ logstash_system_username }}"
    password: "{{ logstash_system_password }}"
    force_basic_auth: yes
    validate_certs: no
  when: logstash_auto_create_elastic_user
  # If found errors in ELK cluster mode
  # run_once: true

- name: Create internal user in Elasticsearch
  uri:
    url: "{{ logstash_elasticsearch_hosts | first }}/_security/user/{{ logstash_user_name }}"
    method: POST
    body_format: json
    body: '{ "password" : "{{ logstash_user_password }}","roles" : ["{{ logstash_role_name }}"],"full_name" : "Internal Logstash User"}'
    status_code: 200
    user: "{{ logstash_system_username }}"
    password: "{{ logstash_system_password }}"
    force_basic_auth: yes
    validate_certs: no
  when: logstash_auto_create_elastic_user
  # If found errors in ELK cluster mode
  # run_once: true