---
- name: Install from official repository
  include: install.yml

- name: Apply default configurations
  include: configuration.yml
- name: Install and verify plugins from configs
  include: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
