---
- name: Converge
  hosts: all
  become: true

  vars:
    logstash_enabled_on_boot: false

  pre_tasks:
    - name: Update apt cache.
      apt: 
        update_cache: true

    - name: Install python3-apt
      raw: apt-get install -y python-apt

    - name: Use Java 8
      set_fact:
        java_packages:
          - openjdk-8-jdk

  roles:
    - ansible-role-java
    - ansible-role-elasticsearch

  tasks:
    - ansible.builtin.include_role:
        name: infra.logstash
    - name: Check logstach status
      ansible.builtin.systemd:
        state: started
        name: logstash.service

